<?php
use App\Models\Currency;
use Illuminate\Database\Seeder;

class CurrencyTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Currency::create(['currency_symbol'=>'USD', 'currency_name'=>'USD - US Dollar']);
        Currency::create(['currency_symbol'=>'AED', 'currency_name'=>'AED - United Arab Emirates Dirham']);
        Currency::create(['currency_symbol'=>'AFN', 'currency_name'=>'AFN - Afghan Afghani']);
        Currency::create(['currency_symbol'=>'ALL', 'currency_name'=>'ALL - Albanian Lek']);
        Currency::create(['currency_symbol'=>'AMD', 'currency_name'=>'AMD - Armenian Dram']);
        Currency::create(['currency_symbol'=>'ANG', 'currency_name'=>'ANG - Netherlands Antillean Guilder']);
        Currency::create(['currency_symbol'=>'AOA', 'currency_name'=>'AOA - Angolan Kwanza']);
        Currency::create(['currency_symbol'=>'ARS', 'currency_name'=>'ARS - Argentine Peso']);
        Currency::create(['currency_symbol'=>'AUD', 'currency_name'=>'AUD - Australian Dollar']);
        Currency::create(['currency_symbol'=>'AWG', 'currency_name'=>'AWG - Aruban Florin']);
        Currency::create(['currency_symbol'=>'AZN', 'currency_name'=>'AZN - Azerbaijani Manat']);
        Currency::create(['currency_symbol'=>'BAM', 'currency_name'=>'BAM - Bosnia-Herzegovina Convertible Mark']);
        Currency::create(['currency_symbol'=>'BBD', 'currency_name'=>'BBD - Barbadian Dollar']);
        Currency::create(['currency_symbol'=>'BDT', 'currency_name'=>'BDT - Bangladeshi Taka']);
        Currency::create(['currency_symbol'=>'BGN', 'currency_name'=>'BGN - Bulgarian Lev']);
        Currency::create(['currency_symbol'=>'BIF', 'currency_name'=>'BIF - Burundian Franc']);
        Currency::create(['currency_symbol'=>'BMD', 'currency_name'=>'BMD - Bermudan Dollar']);
        Currency::create(['currency_symbol'=>'BND', 'currency_name'=>'BND - Brunei Dollar']);
        Currency::create(['currency_symbol'=>'BOB', 'currency_name'=>'BOB - Bolivian Boliviano']);
        Currency::create(['currency_symbol'=>'BRL', 'currency_name'=>'BRL - Brazilian Real']);
        Currency::create(['currency_symbol'=>'BSD', 'currency_name'=>'BSD - Bahamian Dollar']);
        Currency::create(['currency_symbol'=>'BWP', 'currency_name'=>'BWP - Botswanan Pula']);
        Currency::create(['currency_symbol'=>'BZD', 'currency_name'=>'BZD - Belize Dollar']);
        Currency::create(['currency_symbol'=>'CAD', 'currency_name'=>'CAD - Canadian Dollar']);
        Currency::create(['currency_symbol'=>'CDF', 'currency_name'=>'CDF - Congolese Franc']);
        Currency::create(['currency_symbol'=>'CHF', 'currency_name'=>'CHF - Swiss Franc']);
        Currency::create(['currency_symbol'=>'CLP', 'currency_name'=>'CLP - Chilean Peso']);
        Currency::create(['currency_symbol'=>'CNY', 'currency_name'=>'CNY - Chinese Yuan']);
        Currency::create(['currency_symbol'=>'COP', 'currency_name'=>'COP - Colombian Peso']);
        Currency::create(['currency_symbol'=>'CRC', 'currency_name'=>'CRC - Costa Rican Colón']);
        Currency::create(['currency_symbol'=>'CVE', 'currency_name'=>'CVE - Cape Verdean Escudo']);
        Currency::create(['currency_symbol'=>'CZK', 'currency_name'=>'CZK - Czech Koruna']);
        Currency::create(['currency_symbol'=>'DJF', 'currency_name'=>'DJF - Djiboutian Franc']);
        Currency::create(['currency_symbol'=>'DKK', 'currency_name'=>'DKK - Danish Krone']);
        Currency::create(['currency_symbol'=>'DOP', 'currency_name'=>'DOP - Dominican Peso']);
        Currency::create(['currency_symbol'=>'DZD', 'currency_name'=>'DZD - Algerian Dinar']);
        Currency::create(['currency_symbol'=>'EGP', 'currency_name'=>'EGP - Egyptian Pound']);
        Currency::create(['currency_symbol'=>'ETB', 'currency_name'=>'ETB - Ethiopian Birr']);
        Currency::create(['currency_symbol'=>'EUR', 'currency_name'=>'EUR - Euro']);
        Currency::create(['currency_symbol'=>'FJD', 'currency_name'=>'FJD - Fijian Dollar']);
        Currency::create(['currency_symbol'=>'FKP', 'currency_name'=>'FKP - Falkland Islands Pound']);
        Currency::create(['currency_symbol'=>'GBP', 'currency_name'=>'GBP - British Pound']);
        Currency::create(['currency_symbol'=>'GEL', 'currency_name'=>'GEL - Georgian Lari']);
        Currency::create(['currency_symbol'=>'GIP', 'currency_name'=>'GIP - Gibraltar Pound']);
        Currency::create(['currency_symbol'=>'GMD', 'currency_name'=>'GMD - Gambian Dalasi']);
        Currency::create(['currency_symbol'=>'GNF', 'currency_name'=>'GNF - Guinean Franc']);
        Currency::create(['currency_symbol'=>'GTQ', 'currency_name'=>'GTQ - Guatemalan Quetzal']);
        Currency::create(['currency_symbol'=>'GYD', 'currency_name'=>'GYD - Guyanaese Dollar']);
        Currency::create(['currency_symbol'=>'HKD', 'currency_name'=>'HKD - Hong Kong Dollar']);
        Currency::create(['currency_symbol'=>'HNL', 'currency_name'=>'HNL - Honduran Lempira']);
        Currency::create(['currency_symbol'=>'HRK', 'currency_name'=>'HRK - Croatian Kuna']);
        Currency::create(['currency_symbol'=>'HTG', 'currency_name'=>'HTG - Haitian Gourde']);
        Currency::create(['currency_symbol'=>'HUF', 'currency_name'=>'HUF - Hungarian Forint']);
        Currency::create(['currency_symbol'=>'IDR', 'currency_name'=>'IDR - Indonesian Rupiah']);
        Currency::create(['currency_symbol'=>'ILS', 'currency_name'=>'ILS - Israeli New Shekel']);
        Currency::create(['currency_symbol'=>'INR', 'currency_name'=>'INR - Indian Rupee']);
        Currency::create(['currency_symbol'=>'ISK', 'currency_name'=>'ISK - Icelandic Króna']);
        Currency::create(['currency_symbol'=>'JMD', 'currency_name'=>'JMD - Jamaican Dollar']);
        Currency::create(['currency_symbol'=>'JPY', 'currency_name'=>'JPY - Japanese Yen']);
        Currency::create(['currency_symbol'=>'KES', 'currency_name'=>'KES - Kenyan Shilling']);
        Currency::create(['currency_symbol'=>'KGS', 'currency_name'=>'KGS - Kyrgystani Som']);
        Currency::create(['currency_symbol'=>'KHR', 'currency_name'=>'KHR - Cambodian Riel']);
        Currency::create(['currency_symbol'=>'KMF', 'currency_name'=>'KMF - Comorian Franc']);
        Currency::create(['currency_symbol'=>'KRW', 'currency_name'=>'KRW - South Korean Won']);
        Currency::create(['currency_symbol'=>'KYD', 'currency_name'=>'KYD - Cayman Islands Dollar']);
        Currency::create(['currency_symbol'=>'KZT', 'currency_name'=>'KZT - Kazakhstani Tenge']);
        Currency::create(['currency_symbol'=>'LAK', 'currency_name'=>'LAK - Laotian Kip']);
        Currency::create(['currency_symbol'=>'LBP', 'currency_name'=>'LBP - Lebanese Pound']);
        Currency::create(['currency_symbol'=>'LKR', 'currency_name'=>'LKR - Sri Lankan Rupee']);
        Currency::create(['currency_symbol'=>'LRD', 'currency_name'=>'LRD - Liberian Dollar']);
        Currency::create(['currency_symbol'=>'LSL', 'currency_name'=>'LSL - Lesotho Loti']);
        Currency::create(['currency_symbol'=>'MAD', 'currency_name'=>'MAD - Moroccan Dirham']);
        Currency::create(['currency_symbol'=>'MDL', 'currency_name'=>'MDL - Moldovan Leu']);
        Currency::create(['currency_symbol'=>'MGA', 'currency_name'=>'MGA - Malagasy Ariary']);
        Currency::create(['currency_symbol'=>'MKD', 'currency_name'=>'MKD - Macedonian Denar']);
        Currency::create(['currency_symbol'=>'MMK', 'currency_name'=>'MMK - Myanmar Kyat']);
        Currency::create(['currency_symbol'=>'MNT', 'currency_name'=>'MNT - Mongolian Tugrik']);
        Currency::create(['currency_symbol'=>'MOP', 'currency_name'=>'MOP - Macanese Pataca']);
        Currency::create(['currency_symbol'=>'MRO', 'currency_name'=>'MRO - Mauritanian Ouguiya (1973–2017']);
        Currency::create(['currency_symbol'=>'MUR', 'currency_name'=>'MUR - Mauritian Rupee']);
        Currency::create(['currency_symbol'=>'MVR', 'currency_name'=>'MVR - Maldivian Rufiyaa']);
        Currency::create(['currency_symbol'=>'MWK', 'currency_name'=>'MWK - Malawian Kwacha']);
        Currency::create(['currency_symbol'=>'MXN', 'currency_name'=>'MXN - Mexican Peso']);
        Currency::create(['currency_symbol'=>'MYR', 'currency_name'=>'MYR - Malaysian Ringgit']);
        Currency::create(['currency_symbol'=>'MZN', 'currency_name'=>'MZN - Mozambican Metical']);
        Currency::create(['currency_symbol'=>'NAD', 'currency_name'=>'NAD - Namibian Dollar']);
        Currency::create(['currency_symbol'=>'NGN', 'currency_name'=>'NGN - Nigerian Naira']);
        Currency::create(['currency_symbol'=>'NIO', 'currency_name'=>'NIO - Nicaraguan Córdoba']);
        Currency::create(['currency_symbol'=>'NOK', 'currency_name'=>'NOK - Norwegian Krone']);
        Currency::create(['currency_symbol'=>'NPR', 'currency_name'=>'NPR - Nepalese Rupee']);
        Currency::create(['currency_symbol'=>'NZD', 'currency_name'=>'NZD - New Zealand Dollar']);
        Currency::create(['currency_symbol'=>'PAB', 'currency_name'=>'PAB - Panamanian Balboa']);
        Currency::create(['currency_symbol'=>'PEN', 'currency_name'=>'PEN - Peruvian Sol']);
        Currency::create(['currency_symbol'=>'PGK', 'currency_name'=>'PGK - Papua New Guinean Kina']);
        Currency::create(['currency_symbol'=>'PHP', 'currency_name'=>'PHP - Philippine Piso']);
        Currency::create(['currency_symbol'=>'PKR', 'currency_name'=>'PKR - Pakistani Rupee']);
        Currency::create(['currency_symbol'=>'PLN', 'currency_name'=>'PLN - Polish Zloty']);
        Currency::create(['currency_symbol'=>'PYG', 'currency_name'=>'PYG - Paraguayan Guarani']);
        Currency::create(['currency_symbol'=>'QAR', 'currency_name'=>'QAR - Qatari Rial']);
        Currency::create(['currency_symbol'=>'RON', 'currency_name'=>'RON - Romanian Leu']);
        Currency::create(['currency_symbol'=>'RSD', 'currency_name'=>'RSD - Serbian Dinar']);
        Currency::create(['currency_symbol'=>'RUB', 'currency_name'=>'RUB - Russian Ruble']);
        Currency::create(['currency_symbol'=>'RWF', 'currency_name'=>'RWF - Rwandan Franc']);
        Currency::create(['currency_symbol'=>'SAR', 'currency_name'=>'SAR - Saudi Riyal']);
        Currency::create(['currency_symbol'=>'SBD', 'currency_name'=>'SBD - Solomon Islands Dollar']);
        Currency::create(['currency_symbol'=>'SCR', 'currency_name'=>'SCR - Seychellois Rupee']);
        Currency::create(['currency_symbol'=>'SEK', 'currency_name'=>'SEK - Swedish Krona']);
        Currency::create(['currency_symbol'=>'SGD', 'currency_name'=>'SGD - Singapore Dollar']);
        Currency::create(['currency_symbol'=>'SHP', 'currency_name'=>'SHP - St. Helena Pound']);
        Currency::create(['currency_symbol'=>'SLL', 'currency_name'=>'SLL - Sierra Leonean Leone']);
        Currency::create(['currency_symbol'=>'SOS', 'currency_name'=>'SOS - Somali Shilling']);
        Currency::create(['currency_symbol'=>'SRD', 'currency_name'=>'SRD - Surinamese Dollar']);
        Currency::create(['currency_symbol'=>'STD', 'currency_name'=>'STD - São Tomé &amp; Príncipe Dobra (1977–2017']);
        Currency::create(['currency_symbol'=>'SZL', 'currency_name'=>'SZL - Swazi Lilangeni']);
        Currency::create(['currency_symbol'=>'THB', 'currency_name'=>'THB - Thai Baht']);
        Currency::create(['currency_symbol'=>'TJS', 'currency_name'=>'TJS - Tajikistani Somoni']);
        Currency::create(['currency_symbol'=>'TOP', 'currency_name'=>'TOP - Tongan Paʻanga']);
        Currency::create(['currency_symbol'=>'TRY', 'currency_name'=>'TRY - Turkish Lira']);
        Currency::create(['currency_symbol'=>'TTD', 'currency_name'=>'TTD - Trinidad &amp; Tobago Dollar']);
        Currency::create(['currency_symbol'=>'TWD', 'currency_name'=>'TWD - New Taiwan Dollar']);
        Currency::create(['currency_symbol'=>'TZS', 'currency_name'=>'TZS - Tanzanian Shilling']);
        Currency::create(['currency_symbol'=>'UAH', 'currency_name'=>'UAH - Ukrainian Hryvnia']);
        Currency::create(['currency_symbol'=>'UGX', 'currency_name'=>'UGX - Ugandan Shilling']);
        Currency::create(['currency_symbol'=>'UYU', 'currency_name'=>'UYU - Uruguayan Peso']);
        Currency::create(['currency_symbol'=>'UZS', 'currency_name'=>'UZS - Uzbekistani Som']);
        Currency::create(['currency_symbol'=>'VND', 'currency_name'=>'VND - Vietnamese Dong']);
        Currency::create(['currency_symbol'=>'VUV', 'currency_name'=>'VUV - Vanuatu Vatu']);
        Currency::create(['currency_symbol'=>'WST', 'currency_name'=>'WST - Samoan Tala']);
        Currency::create(['currency_symbol'=>'XAF', 'currency_name'=>'XAF - Central African CFA Franc']);
        Currency::create(['currency_symbol'=>'XCD', 'currency_name'=>'XCD - East Caribbean Dollar']);
        Currency::create(['currency_symbol'=>'XOF', 'currency_name'=>'XOF - West African CFA Franc']);
        Currency::create(['currency_symbol'=>'XPF', 'currency_name'=>'XPF - CFP Franc']);
        Currency::create(['currency_symbol'=>'YER', 'currency_name'=>'YER - Yemeni Rial']);
        Currency::create(['currency_symbol'=>'ZAR', 'currency_name'=>'ZAR - South African Rand']);
        Currency::create(['currency_symbol'=>'ZMW', 'currency_name'=>'ZMW - Zambian Kwacha']);
    }
}
