function validate(node) {
  var blur = $("#" + node).data('blur');
  if (blur == 'true' && $("#" + node).val().length != 10) {
    console.log(node + " isn't valid");
    if ($("#error-msg_" + node)) {
      $("#error-msg_" + node).remove();
    };
    $("#tax-id-info_" + node).after(`<span style="color:red;" id="error-msg_${node}">This Tax ID is invalid</span>`);
  }
  else if (blur == 'true' && $("#" + node).val().length == 10) {
    console.log(node + "is valid");
    if ($("#error-msg_" + node)) {
      $("#error-msg_" + node).remove();
    };
  }

}
function start_validate(node) {
  $("#" + node).data('blur', "true");
  validate(node);
}
$(document).ready(function () {
  // Loading array data
  var countries = [
    { id: 'none', text: 'Choose a country...' },
    { id: 'Afghanistan', text: 'Afghanistan' },
    { id: 'Albania', text: 'Albania' },
    { id: 'Algeria', text: 'Algeria' },
    { id: 'American Samoa', text: 'American Samoa' },
    { id: 'Andorra', text: 'Andorra' },
    { id: 'Angola', text: 'Angola' },
    { id: 'Anguilla', text: 'Anguilla' },
    { id: 'Antarctica', text: 'Antarctica' },
    { id: 'Antigua &amp; Barbuda', text: 'Antigua &amp; Barbuda' },
    { id: 'Argentina', text: 'Argentina' },
    { id: 'Armenia', text: 'Armenia' },
    { id: 'Aruba', text: 'Aruba' },
    { id: 'Australia', text: 'Australia' },
    { id: 'Austria', text: 'Austria' },
    { id: 'Azerbaijan', text: 'Azerbaijan' },
    { id: 'Bahamas', text: 'Bahamas' },
    { id: 'Bahrain', text: 'Bahrain' },
    { id: 'Bangladesh', text: 'Bangladesh' },
    { id: 'Barbados', text: 'Barbados' },
    { id: 'Belarus', text: 'Belarus' },
    { id: 'Belgium', text: 'Belgium' },
    { id: 'Belize', text: 'Belize' },
    { id: 'Benin', text: 'Benin' },
    { id: 'Bermuda', text: 'Bermuda' },
    { id: 'Bhutan', text: 'Bhutan' },
    { id: 'Bolivia', text: 'Bolivia' },
    { id: 'Bosnia &amp; Herzegovina', text: 'Bosnia &amp; Herzegovina' },
    { id: 'Botswana', text: 'Botswana' },
    { id: 'Bouvet Island', text: 'Bouvet Island' },
    { id: 'Brazil', text: 'Brazil' },
    { id: 'British Indian Ocean Territory', text: 'British Indian Ocean Territory' },
    { id: 'British Virgin Islands', text: 'British Virgin Islands' },
    { id: 'Brunei', text: 'Brunei' },
    { id: 'Bulgaria', text: 'Bulgaria' },
    { id: 'Burkina Faso', text: 'Burkina Faso' },
    { id: 'Burundi', text: 'Burundi' },
    { id: 'Cambodia', text: 'Cambodia' },
    { id: 'Cameroon', text: 'Cameroon' },
    { id: 'Canada', text: 'Canada' },
    { id: 'Cape Verde', text: 'Cape Verde' },
    { id: 'Caribbean Netherlands', text: 'Caribbean Netherlands' },
    { id: 'Cayman Islands', text: 'Cayman Islands' },
    { id: 'Central African Republic', text: 'Central African Republic' },
    { id: 'Chad', text: 'Chad' },
    { id: 'Chile', text: 'Chile' },
    { id: 'China', text: 'China' },
    { id: 'Choose a country…', text: 'Choose a country…' },
    { id: 'Christmas Island', text: 'Christmas Island' },
    { id: 'Cocos (Keeling) Islands', text: 'Cocos (Keeling) Islands' },
    { id: 'Colombia', text: 'Colombia' },
    { id: 'Comoros', text: 'Comoros' },
    { id: 'Congo - Brazzaville', text: 'Congo - Brazzaville' },
    { id: 'Congo - Kinshasa', text: 'Congo - Kinshasa' },
    { id: 'Cook Islands', text: 'Cook Islands' },
    { id: 'Costa Rica', text: 'Costa Rica' },
    { id: 'Croatia', text: 'Croatia' },
    { id: 'Cuba', text: 'Cuba' },
    { id: 'Curaçao', text: 'Curaçao' },
    { id: 'Cyprus', text: 'Cyprus' },
    { id: 'Czech Republic', text: 'Czech Republic' },
    { id: 'Côte d’Ivoire', text: 'Côte d’Ivoire' },
    { id: 'Denmark', text: 'Denmark' },
    { id: 'Djibouti', text: 'Djibouti' },
    { id: 'Dominica', text: 'Dominica' },
    { id: 'Dominican Republic', text: 'Dominican Republic' },
    { id: 'Ecuador', text: 'Ecuador' },
    { id: 'Egypt', text: 'Egypt' },
    { id: 'El Salvador', text: 'El Salvador' },
    { id: 'Equatorial Guinea', text: 'Equatorial Guinea' },
    { id: 'Eritrea', text: 'Eritrea' },
    { id: 'Estonia', text: 'Estonia' },
    { id: 'Eswatini', text: 'Eswatini' },
    { id: 'Ethiopia', text: 'Ethiopia' },
    { id: 'Falkland Islands', text: 'Falkland Islands' },
    { id: 'Faroe Islands', text: 'Faroe Islands' },
    { id: 'Fiji', text: 'Fiji' },
    { id: 'Finland', text: 'Finland' },
    { id: 'France', text: 'France' },
    { id: 'French Guiana', text: 'French Guiana' },
    { id: 'French Polynesia', text: 'French Polynesia' },
    { id: 'French Southern Territories', text: 'French Southern Territories' },
    { id: 'Gabon', text: 'Gabon' },
    { id: 'Gambia', text: 'Gambia' },
    { id: 'Georgia', text: 'Georgia' },
    { id: 'Germany', text: 'Germany' },
    { id: 'Ghana', text: 'Ghana' },
    { id: 'Gibraltar', text: 'Gibraltar' },
    { id: 'Greece', text: 'Greece' },
    { id: 'Greenland', text: 'Greenland' },
    { id: 'Grenada', text: 'Grenada' },
    { id: 'Guadeloupe', text: 'Guadeloupe' },
    { id: 'Guam', text: 'Guam' },
    { id: 'Guatemala', text: 'Guatemala' },
    { id: 'Guernsey', text: 'Guernsey' },
    { id: 'Guinea', text: 'Guinea' },
    { id: 'Guinea-Bissau', text: 'Guinea-Bissau' },
    { id: 'Guyana', text: 'Guyana' },
    { id: 'Haiti', text: 'Haiti' },
    { id: 'Heard &amp; McDonald Islands', text: 'Heard &amp; McDonald Islands' },
    { id: 'Honduras', text: 'Honduras' },
    { id: 'Hong Kong SAR China', text: 'Hong Kong SAR China' },
    { id: 'Hungary', text: 'Hungary' },
    { id: 'Iceland', text: 'Iceland' },
    { id: 'India', text: 'India' },
    { id: 'Indonesia', text: 'Indonesia' },
    { id: 'Iran', text: 'Iran' },
    { id: 'Iraq', text: 'Iraq' },
    { id: 'Ireland', text: 'Ireland' },
    { id: 'Isle of Man', text: 'Isle of Man' },
    { id: 'Israel', text: 'Israel' },
    { id: 'Italy', text: 'Italy' },
    { id: 'Jamaica', text: 'Jamaica' },
    { id: 'Japan', text: 'Japan' },
    { id: 'Jersey', text: 'Jersey' },
    { id: 'Jordan', text: 'Jordan' },
    { id: 'Kazakhstan', text: 'Kazakhstan' },
    { id: 'Kenya', text: 'Kenya' },
    { id: 'Kiribati', text: 'Kiribati' },
    { id: 'Kuwait', text: 'Kuwait' },
    { id: 'Kyrgyzstan', text: 'Kyrgyzstan' },
    { id: 'Laos', text: 'Laos' },
    { id: 'Latvia', text: 'Latvia' },
    { id: 'Lebanon', text: 'Lebanon' },
    { id: 'Lesotho', text: 'Lesotho' },
    { id: 'Liberia', text: 'Liberia' },
    { id: 'Libya', text: 'Libya' },
    { id: 'Liechtenstein', text: 'Liechtenstein' },
    { id: 'Lithuania', text: 'Lithuania' },
    { id: 'Luxembourg', text: 'Luxembourg' },
    { id: 'Macao SAR China', text: 'Macao SAR China' },
    { id: 'Madagascar', text: 'Madagascar' },
    { id: 'Malawi', text: 'Malawi' },
    { id: 'Malaysia', text: 'Malaysia' },
    { id: 'Maldives', text: 'Maldives' },
    { id: 'Mali', text: 'Mali' },
    { id: 'Malta', text: 'Malta' },
    { id: 'Marshall Islands', text: 'Marshall Islands' },
    { id: 'Martinique', text: 'Martinique' },
    { id: 'Mauritania', text: 'Mauritania' },
    { id: 'Mauritius', text: 'Mauritius' },
    { id: 'Mayotte', text: 'Mayotte' },
    { id: 'Mexico', text: 'Mexico' },
    { id: 'Micronesia', text: 'Micronesia' },
    { id: 'Moldova', text: 'Moldova' },
    { id: 'Monaco', text: 'Monaco' },
    { id: 'Mongolia', text: 'Mongolia' },
    { id: 'Montenegro', text: 'Montenegro' },
    { id: 'Montserrat', text: 'Montserrat' },
    { id: 'Morocco', text: 'Morocco' },
    { id: 'Mozambique', text: 'Mozambique' },
    { id: 'Myanmar (Burma)', text: 'Myanmar (Burma)' },
    { id: 'Namibia', text: 'Namibia' },
    { id: 'Nauru', text: 'Nauru' },
    { id: 'Nepal', text: 'Nepal' },
    { id: 'Netherlands', text: 'Netherlands' },
    { id: 'New Caledonia', text: 'New Caledonia' },
    { id: 'New Zealand', text: 'New Zealand' },
    { id: 'Nicaragua', text: 'Nicaragua' },
    { id: 'Niger', text: 'Niger' },
    { id: 'Nigeria', text: 'Nigeria' },
    { id: 'Niue', text: 'Niue' },
    { id: 'Norfolk Island', text: 'Norfolk Island' },
    { id: 'North Korea', text: 'North Korea' },
    { id: 'North Macedonia', text: 'North Macedonia' },
    { id: 'Northern Mariana Islands', text: 'Northern Mariana Islands' },
    { id: 'Norway', text: 'Norway' },
    { id: 'Oman', text: 'Oman' },
    { id: 'Pakistan', text: 'Pakistan' },
    { id: 'Palau', text: 'Palau' },
    { id: 'Palestinian Territories', text: 'Palestinian Territories' },
    { id: 'Panama', text: 'Panama' },
    { id: 'Papua New Guinea', text: 'Papua New Guinea' },
    { id: 'Paraguay', text: 'Paraguay' },
    { id: 'Peru', text: 'Peru' },
    { id: 'Philippines', text: 'Philippines' },
    { id: 'Pitcairn Islands', text: 'Pitcairn Islands' },
    { id: 'Poland', text: 'Poland' },
    { id: 'Portugal', text: 'Portugal' },
    { id: 'Puerto Rico', text: 'Puerto Rico' },
    { id: 'Qatar', text: 'Qatar' },
    { id: 'Romania', text: 'Romania' },
    { id: 'Russia', text: 'Russia' },
    { id: 'Rwanda', text: 'Rwanda' },
    { id: 'Réunion', text: 'Réunion' },
    { id: 'Samoa', text: 'Samoa' },
    { id: 'San Marino', text: 'San Marino' },
    { id: 'Saudi Arabia', text: 'Saudi Arabia' },
    { id: 'Senegal', text: 'Senegal' },
    { id: 'Serbia', text: 'Serbia' },
    { id: 'Seychelles', text: 'Seychelles' },
    { id: 'Sierra Leone', text: 'Sierra Leone' },
    { id: 'Singapore', text: 'Singapore' },
    { id: 'Sint Maarten', text: 'Sint Maarten' },
    { id: 'Slovakia', text: 'Slovakia' },
    { id: 'Slovenia', text: 'Slovenia' },
    { id: 'Solomon Islands', text: 'Solomon Islands' },
    { id: 'Somalia', text: 'Somalia' },
    { id: 'South Africa', text: 'South Africa' },
    { id: 'South Georgia &amp; South Sandwich Islands', text: 'South Georgia &amp; South Sandwich Islands' },
    { id: 'South Korea', text: 'South Korea' },
    { id: 'South Sudan', text: 'South Sudan' },
    { id: 'Spain', text: 'Spain' },
    { id: 'Sri Lanka', text: 'Sri Lanka' },
    { id: 'St. Barthélemy', text: 'St. Barthélemy' },
    { id: 'St. Helena', text: 'St. Helena' },
    { id: 'St. Kitts &amp; Nevis', text: 'St. Kitts &amp; Nevis' },
    { id: 'St. Lucia', text: 'St. Lucia' },
    { id: 'St. Martin', text: 'St. Martin' },
    { id: 'St. Pierre &amp; Miquelon', text: 'St. Pierre &amp; Miquelon' },
    { id: 'St. Vincent &amp; Grenadines', text: 'St. Vincent &amp; Grenadines' },
    { id: 'Sudan', text: 'Sudan' },
    { id: 'Suriname', text: 'Suriname' },
    { id: 'Svalbard &amp; Jan Mayen', text: 'Svalbard &amp; Jan Mayen' },
    { id: 'Sweden', text: 'Sweden' },
    { id: 'Switzerland', text: 'Switzerland' },
    { id: 'Syria', text: 'Syria' },
    { id: 'São Tomé &amp; Príncipe', text: 'São Tomé &amp; Príncipe' },
    { id: 'Taiwan', text: 'Taiwan' },
    { id: 'Tajikistan', text: 'Tajikistan' },
    { id: 'Tanzania', text: 'Tanzania' },
    { id: 'Thailand', text: 'Thailand' },
    { id: 'Timor-Leste', text: 'Timor-Leste' },
    { id: 'Togo', text: 'Togo' },
    { id: 'Tokelau', text: 'Tokelau' },
    { id: 'Tonga', text: 'Tonga' },
    { id: 'Trinidad &amp; Tobago', text: 'Trinidad &amp; Tobago' },
    { id: 'Tunisia', text: 'Tunisia' },
    { id: 'Turkey', text: 'Turkey' },
    { id: 'Turkmenistan', text: 'Turkmenistan' },
    { id: 'Turks &amp; Caicos Islands', text: 'Turks &amp; Caicos Islands' },
    { id: 'Tuvalu', text: 'Tuvalu' },
    { id: 'U.S. Outlying Islands', text: 'U.S. Outlying Islands' },
    { id: 'U.S. Virgin Islands', text: 'U.S. Virgin Islands' },
    { id: 'Uganda', text: 'Uganda' },
    { id: 'Ukraine', text: 'Ukraine' },
    { id: 'United Arab Emirates', text: 'United Arab Emirates' },
    { id: 'United Kingdom', text: 'United Kingdom' },
    { id: 'United States', text: 'United States' },
    { id: 'Uruguay', text: 'Uruguay' },
    { id: 'Uzbekistan', text: 'Uzbekistan' },
    { id: 'Vanuatu', text: 'Vanuatu' },
    { id: 'Vatican City', text: 'Vatican City' },
    { id: 'Venezuela', text: 'Venezuela' },
    { id: 'Vietnam', text: 'Vietnam' },
    { id: 'Wallis &amp; Futuna', text: 'Wallis &amp; Futuna' },
    { id: 'Western Sahara', text: 'Western Sahara' },
    { id: 'Yemen', text: 'Yemen' },
    { id: 'Zambia', text: 'Zambia' },
    { id: 'Zimbabwe', text: 'Zimbabwe' },
    { id: 'Åland Islands', text: 'Åland Islands' },
  ];

  var timezones = [
    { id: 'none', text: 'Choose a time zone...' },
    { id: 'Africa - Abidjan', text: 'Africa - Abidjan' },
    { id: 'Africa - Accra', text: 'Africa - Accra' },
    { id: 'Africa - Addis Ababa', text: 'Africa - Addis Ababa' },
    { id: 'Africa - Algiers', text: 'Africa - Algiers' },
    { id: 'Africa - Asmara', text: 'Africa - Asmara' },
    { id: 'Africa - Asmera', text: 'Africa - Asmera' },
    { id: 'Africa - Bamako', text: 'Africa - Bamako' },
    { id: 'Africa - Bangui', text: 'Africa - Bangui' },
    { id: 'Africa - Banjul', text: 'Africa - Banjul' },
    { id: 'Africa - Bissau', text: 'Africa - Bissau' },
    { id: 'Africa - Blantyre', text: 'Africa - Blantyre' },
    { id: 'Africa - Brazzaville', text: 'Africa - Brazzaville' },
    { id: 'Africa - Bujumbura', text: 'Africa - Bujumbura' },
    { id: 'Africa - Cairo', text: 'Africa - Cairo' },
    { id: 'Africa - Casablanca', text: 'Africa - Casablanca' },
    { id: 'Africa - Ceuta', text: 'Africa - Ceuta' },
    { id: 'Africa - Conakry', text: 'Africa - Conakry' },
    { id: 'Africa - Dakar', text: 'Africa - Dakar' },
    { id: 'Africa - Dar es Salaam', text: 'Africa - Dar es Salaam' },
    { id: 'Africa - Djibouti', text: 'Africa - Djibouti' },
    { id: 'Africa - Douala', text: 'Africa - Douala' },
    { id: 'Africa - El Aaiun', text: 'Africa - El Aaiun' },
    { id: 'Africa - Freetown', text: 'Africa - Freetown' },
    { id: 'Africa - Gaborone', text: 'Africa - Gaborone' },
    { id: 'Africa - Harare', text: 'Africa - Harare' },
    { id: 'Africa - Johannesburg', text: 'Africa - Johannesburg' },
    { id: 'Africa - Juba', text: 'Africa - Juba' },
    { id: 'Africa - Kampala', text: 'Africa - Kampala' },
    { id: 'Africa - Khartoum', text: 'Africa - Khartoum' },
    { id: 'Africa - Kigali', text: 'Africa - Kigali' },
    { id: 'Africa - Kinshasa', text: 'Africa - Kinshasa' },
    { id: 'Africa - Lagos', text: 'Africa - Lagos' },
    { id: 'Africa - Libreville', text: 'Africa - Libreville' },
    { id: 'Africa - Lome', text: 'Africa - Lome' },
    { id: 'Africa - Luanda', text: 'Africa - Luanda' },
    { id: 'Africa - Lubumbashi', text: 'Africa - Lubumbashi' },
    { id: 'Africa - Lusaka', text: 'Africa - Lusaka' },
    { id: 'Africa - Malabo', text: 'Africa - Malabo' },
    { id: 'Africa - Maputo', text: 'Africa - Maputo' },
    { id: 'Africa - Maseru', text: 'Africa - Maseru' },
    { id: 'Africa - Mbabane', text: 'Africa - Mbabane' },
    { id: 'Africa - Mogadishu', text: 'Africa - Mogadishu' },
    { id: 'Africa - Monrovia', text: 'Africa - Monrovia' },
    { id: 'Africa - Nairobi', text: 'Africa - Nairobi' },
    { id: 'Africa - Ndjamena', text: 'Africa - Ndjamena' },
    { id: 'Africa - Niamey', text: 'Africa - Niamey' },
    { id: 'Africa - Nouakchott', text: 'Africa - Nouakchott' },
    { id: 'Africa - Ouagadougou', text: 'Africa - Ouagadougou' },
    { id: 'Africa - Porto-Novo', text: 'Africa - Porto-Novo' },
    { id: 'Africa - Sao Tome', text: 'Africa - Sao Tome' },
    { id: 'Africa - Timbuktu', text: 'Africa - Timbuktu' },
    { id: 'Africa - Tripoli', text: 'Africa - Tripoli' },
    { id: 'Africa - Tunis', text: 'Africa - Tunis' },
    { id: 'Africa - Windhoek', text: 'Africa - Windhoek' },
    { id: 'America - Adak', text: 'America - Adak' },
    { id: 'America - Anchorage', text: 'America - Anchorage' },
    { id: 'America - Anguilla', text: 'America - Anguilla' },
    { id: 'America - Antigua', text: 'America - Antigua' },
    { id: 'America - Araguaina', text: 'America - Araguaina' },
    { id: 'America - Aruba', text: 'America - Aruba' },
    { id: 'America - Asuncion', text: 'America - Asuncion' },
    { id: 'America - Atikokan', text: 'America - Atikokan' },
    { id: 'America - Atka', text: 'America - Atka' },
    { id: 'America - Bahia', text: 'America - Bahia' },
    { id: 'America - Bahia Banderas', text: 'America - Bahia Banderas' },
    { id: 'America - Barbados', text: 'America - Barbados' },
    { id: 'America - Belem', text: 'America - Belem' },
    { id: 'America - Belize', text: 'America - Belize' },
    { id: 'America - Beulah, North Dakota', text: 'America - Beulah, North Dakota' },
    { id: 'America - Blanc-Sablon', text: 'America - Blanc-Sablon' },
    { id: 'America - Boa Vista', text: 'America - Boa Vista' },
    { id: 'America - Bogota', text: 'America - Bogota' },
    { id: 'America - Boise', text: 'America - Boise' },
    { id: 'America - Buenos Aires', text: 'America - Buenos Aires' },
    { id: 'America - Buenos Aires, Argentina', text: 'America - Buenos Aires, Argentina' },
    { id: 'America - Cambridge Bay', text: 'America - Cambridge Bay' },
    { id: 'America - Campo Grande', text: 'America - Campo Grande' },
    { id: 'America - Cancun', text: 'America - Cancun' },
    { id: 'America - Caracas', text: 'America - Caracas' },
    { id: 'America - Catamarca', text: 'America - Catamarca' },
    { id: 'America - Catamarca, Argentina', text: 'America - Catamarca, Argentina' },
    { id: 'America - Cayenne', text: 'America - Cayenne' },
    { id: 'America - Cayman', text: 'America - Cayman' },
    { id: 'America - Center, North Dakota', text: 'America - Center, North Dakota' },
    { id: 'America - Chicago', text: 'America - Chicago' },
    { id: 'America - Chihuahua', text: 'America - Chihuahua' },
    { id: 'America - Comod Rivadavia, Argentina', text: 'America - Comod Rivadavia, Argentina' },
    { id: 'America - Coral Harbour', text: 'America - Coral Harbour' },
    { id: 'America - Cordoba', text: 'America - Cordoba' },
    { id: 'America - Cordoba, Argentina', text: 'America - Cordoba, Argentina' },
    { id: 'America - Costa Rica', text: 'America - Costa Rica' },
    { id: 'America - Creston', text: 'America - Creston' },
    { id: 'America - Cuiaba', text: 'America - Cuiaba' },
    { id: 'America - Curacao', text: 'America - Curacao' },
    { id: 'America - Danmarkshavn', text: 'America - Danmarkshavn' },
    { id: 'America - Dawson', text: 'America - Dawson' },
    { id: 'America - Dawson Creek', text: 'America - Dawson Creek' },
    { id: 'America - Denver', text: 'America - Denver' },
    { id: 'America - Detroit', text: 'America - Detroit' },
    { id: 'America - Dominica', text: 'America - Dominica' },
    { id: 'America - Edmonton', text: 'America - Edmonton' },
    { id: 'America - Eirunepe', text: 'America - Eirunepe' },
    { id: 'America - El Salvador', text: 'America - El Salvador' },
    { id: 'America - Ensenada', text: 'America - Ensenada' },
    { id: 'America - Fort Nelson', text: 'America - Fort Nelson' },
    { id: 'America - Fort Wayne', text: 'America - Fort Wayne' },
    { id: 'America - Fortaleza', text: 'America - Fortaleza' },
    { id: 'America - Glace Bay', text: 'America - Glace Bay' },
    { id: 'America - Godthab', text: 'America - Godthab' },
    { id: 'America - Goose Bay', text: 'America - Goose Bay' },
    { id: 'America - Grand Turk', text: 'America - Grand Turk' },
    { id: 'America - Grenada', text: 'America - Grenada' },
    { id: 'America - Guadeloupe', text: 'America - Guadeloupe' },
    { id: 'America - Guatemala', text: 'America - Guatemala' },
    { id: 'America - Guayaquil', text: 'America - Guayaquil' },
    { id: 'America - Guyana', text: 'America - Guyana' },
    { id: 'America - Halifax', text: 'America - Halifax' },
    { id: 'America - Havana', text: 'America - Havana' },
    { id: 'America - Hermosillo', text: 'America - Hermosillo' },
    { id: 'America - Indianapolis', text: 'America - Indianapolis' },
    { id: 'America - Indianapolis, Indiana', text: 'America - Indianapolis, Indiana' },
    { id: 'America - Inuvik', text: 'America - Inuvik' },
    { id: 'America - Iqaluit', text: 'America - Iqaluit' },
    { id: 'America - Jamaica', text: 'America - Jamaica' },
    { id: 'America - Jujuy', text: 'America - Jujuy' },
    { id: 'America - Jujuy, Argentina', text: 'America - Jujuy, Argentina' },
    { id: 'America - Juneau', text: 'America - Juneau' },
    { id: "America - Knox I'N", text: "America - Knox I'N" },
    { id: 'America - Knox, Indiana', text: 'America - Knox, Indiana' },
    { id: 'America - Kralendijk', text: 'America - Kralendijk' },
    { id: 'America - La Paz', text: 'America - La Paz' },
    { id: 'America - La Rioja, Argentina', text: 'America - La Rioja, Argentina' },
    { id: 'America - Lima', text: 'America - Lima' },
    { id: 'America - Los Angeles', text: 'America - Los Angeles' },
    { id: 'America - Louisville', text: 'America - Louisville' },
    { id: 'America - Louisville, Kentucky', text: 'America - Louisville, Kentucky' },
    { id: 'America - Lower Princes', text: 'America - Lower Princes' },
    { id: 'America - Maceio', text: 'America - Maceio' },
    { id: 'America - Managua', text: 'America - Managua' },
    { id: 'America - Manaus', text: 'America - Manaus' },
    { id: 'America - Marengo, Indiana', text: 'America - Marengo, Indiana' },
    { id: 'America - Marigot', text: 'America - Marigot' },
    { id: 'America - Martinique', text: 'America - Martinique' },
    { id: 'America - Matamoros', text: 'America - Matamoros' },
    { id: 'America - Mazatlan', text: 'America - Mazatlan' },
    { id: 'America - Mendoza', text: 'America - Mendoza' },
    { id: 'America - Mendoza, Argentina', text: 'America - Mendoza, Argentina' },
    { id: 'America - Menominee', text: 'America - Menominee' },
    { id: 'America - Merida', text: 'America - Merida' },
    { id: 'America - Metlakatla', text: 'America - Metlakatla' },
    { id: 'America - Mexico City', text: 'America - Mexico City' },
    { id: 'America - Miquelon', text: 'America - Miquelon' },
    { id: 'America - Moncton', text: 'America - Moncton' },
    { id: 'America - Monterrey', text: 'America - Monterrey' },
    { id: 'America - Montevideo', text: 'America - Montevideo' },
    { id: 'America - Monticello, Kentucky', text: 'America - Monticello, Kentucky' },
    { id: 'America - Montreal', text: 'America - Montreal' },
    { id: 'America - Montserrat', text: 'America - Montserrat' },
    { id: 'America - Nassau', text: 'America - Nassau' },
    { id: 'America - New Salem, North Dakota', text: 'America - New Salem, North Dakota' },
    { id: 'America - New York', text: 'America - New York' },
    { id: 'America - Nipigon', text: 'America - Nipigon' },
    { id: 'America - Nome', text: 'America - Nome' },
    { id: 'America - Noronha', text: 'America - Noronha' },
    { id: 'America - Ojinaga', text: 'America - Ojinaga' },
    { id: 'America - Panama', text: 'America - Panama' },
    { id: 'America - Pangnirtung', text: 'America - Pangnirtung' },
    { id: 'America - Paramaribo', text: 'America - Paramaribo' },
    { id: 'America - Petersburg, Indiana', text: 'America - Petersburg, Indiana' },
    { id: 'America - Phoenix', text: 'America - Phoenix' },
    { id: 'America - Port of Spain', text: 'America - Port of Spain' },
    { id: 'America - Port-au-Prince', text: 'America - Port-au-Prince' },
    { id: 'America - Porto Acre', text: 'America - Porto Acre' },
    { id: 'America - Porto Velho', text: 'America - Porto Velho' },
    { id: 'America - Puerto Rico', text: 'America - Puerto Rico' },
    { id: 'America - Punta Arenas', text: 'America - Punta Arenas' },
    { id: 'America - Rainy River', text: 'America - Rainy River' },
    { id: 'America - Rankin Inlet', text: 'America - Rankin Inlet' },
    { id: 'America - Recife', text: 'America - Recife' },
    { id: 'America - Regina', text: 'America - Regina' },
    { id: 'America - Resolute', text: 'America - Resolute' },
    { id: 'America - Rio Branco', text: 'America - Rio Branco' },
    { id: 'America - Rio Gallegos, Argentina', text: 'America - Rio Gallegos, Argentina' },
    { id: 'America - Rosario', text: 'America - Rosario' },
    { id: 'America - Salta, Argentina', text: 'America - Salta, Argentina' },
    { id: 'America - San Juan, Argentina', text: 'America - San Juan, Argentina' },
    { id: 'America - San Luis, Argentina', text: 'America - San Luis, Argentina' },
    { id: 'America - Santa Isabel', text: 'America - Santa Isabel' },
    { id: 'America - Santarem', text: 'America - Santarem' },
    { id: 'America - Santiago', text: 'America - Santiago' },
    { id: 'America - Santo Domingo', text: 'America - Santo Domingo' },
    { id: 'America - Sao Paulo', text: 'America - Sao Paulo' },
    { id: 'America - Scoresbysund', text: 'America - Scoresbysund' },
    { id: 'America - Shiprock', text: 'America - Shiprock' },
    { id: 'America - Sitka', text: 'America - Sitka' },
    { id: 'America - St Barthelemy', text: 'America - St Barthelemy' },
    { id: 'America - St Johns', text: 'America - St Johns' },
    { id: 'America - St Kitts', text: 'America - St Kitts' },
    { id: 'America - St Lucia', text: 'America - St Lucia' },
    { id: 'America - St Thomas', text: 'America - St Thomas' },
    { id: 'America - St Vincent', text: 'America - St Vincent' },
    { id: 'America - Swift Current', text: 'America - Swift Current' },
    { id: 'America - Tegucigalpa', text: 'America - Tegucigalpa' },
    { id: 'America - Tell City, Indiana', text: 'America - Tell City, Indiana' },
    { id: 'America - Thule', text: 'America - Thule' },
    { id: 'America - Thunder Bay', text: 'America - Thunder Bay' },
    { id: 'America - Tijuana', text: 'America - Tijuana' },
    { id: 'America - Toronto', text: 'America - Toronto' },
    { id: 'America - Tortola', text: 'America - Tortola' },
    { id: 'America - Tucuman, Argentina', text: 'America - Tucuman, Argentina' },
    { id: 'America - Ushuaia, Argentina', text: 'America - Ushuaia, Argentina' },
    { id: 'America - Vancouver', text: 'America - Vancouver' },
    { id: 'America - Vevay, Indiana', text: 'America - Vevay, Indiana' },
    { id: 'America - Vincennes, Indiana', text: 'America - Vincennes, Indiana' },
    { id: 'America - Virgin', text: 'America - Virgin' },
    { id: 'America - Whitehorse', text: 'America - Whitehorse' },
    { id: 'America - Winamac, Indiana', text: 'America - Winamac, Indiana' },
    { id: 'America - Winnipeg', text: 'America - Winnipeg' },
    { id: 'America - Yakutat', text: 'America - Yakutat' },
    { id: 'America - Yellowknife', text: 'America - Yellowknife' },
    { id: 'Antarctica - Casey', text: 'Antarctica - Casey' },
    { id: 'Antarctica - Davis', text: 'Antarctica - Davis' },
    { id: "Antarctica - Dumont D'Urville", text: "Antarctica - Dumont D'Urville" },
    { id: 'Antarctica - Macquarie', text: 'Antarctica - Macquarie' },
    { id: 'Antarctica - Mawson', text: 'Antarctica - Mawson' },
    { id: 'Antarctica - McMurdo', text: 'Antarctica - McMurdo' },
    { id: 'Antarctica - Palmer', text: 'Antarctica - Palmer' },
    { id: 'Antarctica - Rothera', text: 'Antarctica - Rothera' },
    { id: 'Antarctica - South Pole', text: 'Antarctica - South Pole' },
    { id: 'Antarctica - Syowa', text: 'Antarctica - Syowa' },
    { id: 'Antarctica - Troll', text: 'Antarctica - Troll' },
    { id: 'Antarctica - Vostok', text: 'Antarctica - Vostok' },
    { id: 'Arctic - Longyearbyen', text: 'Arctic - Longyearbyen' },
    { id: 'Asia - Aden', text: 'Asia - Aden' },
    { id: 'Asia - Almaty', text: 'Asia - Almaty' },
    { id: 'Asia - Amman', text: 'Asia - Amman' },
    { id: 'Asia - Anadyr', text: 'Asia - Anadyr' },
    { id: 'Asia - Aqtau', text: 'Asia - Aqtau' },
    { id: 'Asia - Aqtobe', text: 'Asia - Aqtobe' },
    { id: 'Asia - Ashgabat', text: 'Asia - Ashgabat' },
    { id: 'Asia - Ashkhabad', text: 'Asia - Ashkhabad' },
    { id: 'Asia - Atyrau', text: 'Asia - Atyrau' },
    { id: 'Asia - Baghdad', text: 'Asia - Baghdad' },
    { id: 'Asia - Bahrain', text: 'Asia - Bahrain' },
    { id: 'Asia - Baku', text: 'Asia - Baku' },
    { id: 'Asia - Bangkok', text: 'Asia - Bangkok' },
    { id: 'Asia - Barnaul', text: 'Asia - Barnaul' },
    { id: 'Asia - Beirut', text: 'Asia - Beirut' },
    { id: 'Asia - Bishkek', text: 'Asia - Bishkek' },
    { id: 'Asia - Brunei', text: 'Asia - Brunei' },
    { id: 'Asia - Calcutta', text: 'Asia - Calcutta' },
    { id: 'Asia - Chita', text: 'Asia - Chita' },
    { id: 'Asia - Choibalsan', text: 'Asia - Choibalsan' },
    { id: 'Asia - Chongqing', text: 'Asia - Chongqing' },
    { id: 'Asia - Chungking', text: 'Asia - Chungking' },
    { id: 'Asia - Colombo', text: 'Asia - Colombo' },
    { id: 'Asia - Dacca', text: 'Asia - Dacca' },
    { id: 'Asia - Damascus', text: 'Asia - Damascus' },
    { id: 'Asia - Dhaka', text: 'Asia - Dhaka' },
    { id: 'Asia - Dili', text: 'Asia - Dili' },
    { id: 'Asia - Dubai', text: 'Asia - Dubai' },
    { id: 'Asia - Dushanbe', text: 'Asia - Dushanbe' },
    { id: 'Asia - Famagusta', text: 'Asia - Famagusta' },
    { id: 'Asia - Gaza', text: 'Asia - Gaza' },
    { id: 'Asia - Harbin', text: 'Asia - Harbin' },
    { id: 'Asia - Hebron', text: 'Asia - Hebron' },
    { id: 'Asia - Ho Chi Minh', text: 'Asia - Ho Chi Minh' },
    { id: 'Asia - Hong Kong', text: 'Asia - Hong Kong' },
    { id: 'Asia - Hovd', text: 'Asia - Hovd' },
    { id: 'Asia - Irkutsk', text: 'Asia - Irkutsk' },
    { id: 'Asia - Istanbul', text: 'Asia - Istanbul' },
    { id: 'Asia - Jakarta', text: 'Asia - Jakarta' },
    { id: 'Asia - Jayapura', text: 'Asia - Jayapura' },
    { id: 'Asia - Jerusalem', text: 'Asia - Jerusalem' },
    { id: 'Asia - Kabul', text: 'Asia - Kabul' },
    { id: 'Asia - Kamchatka', text: 'Asia - Kamchatka' },
    { id: 'Asia - Karachi', text: 'Asia - Karachi' },
    { id: 'Asia - Kashgar', text: 'Asia - Kashgar' },
    { id: 'Asia - Kathmandu', text: 'Asia - Kathmandu' },
    { id: 'Asia - Katmandu', text: 'Asia - Katmandu' },
    { id: 'Asia - Khandyga', text: 'Asia - Khandyga' },
    { id: 'Asia - Kolkata', text: 'Asia - Kolkata' },
    { id: 'Asia - Krasnoyarsk', text: 'Asia - Krasnoyarsk' },
    { id: 'Asia - Kuala Lumpur', text: 'Asia - Kuala Lumpur' },
    { id: 'Asia - Kuching', text: 'Asia - Kuching' },
    { id: 'Asia - Kuwait', text: 'Asia - Kuwait' },
    { id: 'Asia - Macao', text: 'Asia - Macao' },
    { id: 'Asia - Macau', text: 'Asia - Macau' },
    { id: 'Asia - Magadan', text: 'Asia - Magadan' },
    { id: 'Asia - Makassar', text: 'Asia - Makassar' },
    { id: 'Asia - Manila', text: 'Asia - Manila' },
    { id: 'Asia - Muscat', text: 'Asia - Muscat' },
    { id: 'Asia - Nicosia', text: 'Asia - Nicosia' },
    { id: 'Asia - Novokuznetsk', text: 'Asia - Novokuznetsk' },
    { id: 'Asia - Novosibirsk', text: 'Asia - Novosibirsk' },
    { id: 'Asia - Omsk', text: 'Asia - Omsk' },
    { id: 'Asia - Oral', text: 'Asia - Oral' },
    { id: 'Asia - Phnom Penh', text: 'Asia - Phnom Penh' },
    { id: 'Asia - Pontianak', text: 'Asia - Pontianak' },
    { id: 'Asia - Pyongyang', text: 'Asia - Pyongyang' },
    { id: 'Asia - Qatar', text: 'Asia - Qatar' },
    { id: 'Asia - Qostanay', text: 'Asia - Qostanay' },
    { id: 'Asia - Qyzylorda', text: 'Asia - Qyzylorda' },
    { id: 'Asia - Rangoon', text: 'Asia - Rangoon' },
    { id: 'Asia - Riyadh', text: 'Asia - Riyadh' },
    { id: 'Asia - Saigon', text: 'Asia - Saigon' },
    { id: 'Asia - Sakhalin', text: 'Asia - Sakhalin' },
    { id: 'Asia - Samarkand', text: 'Asia - Samarkand' },
    { id: 'Asia - Seoul', text: 'Asia - Seoul' },
    { id: 'Asia - Shanghai', text: 'Asia - Shanghai' },
    { id: 'Asia - Singapore', text: 'Asia - Singapore' },
    { id: 'Asia - Srednekolymsk', text: 'Asia - Srednekolymsk' },
    { id: 'Asia - Taipei', text: 'Asia - Taipei' },
    { id: 'Asia - Tashkent', text: 'Asia - Tashkent' },
    { id: 'Asia - Tbilisi', text: 'Asia - Tbilisi' },
    { id: 'Asia - Tehran', text: 'Asia - Tehran' },
    { id: 'Asia - Tel Aviv', text: 'Asia - Tel Aviv' },
    { id: 'Asia - Thimbu', text: 'Asia - Thimbu' },
    { id: 'Asia - Thimphu', text: 'Asia - Thimphu' },
    { id: 'Asia - Tokyo', text: 'Asia - Tokyo' },
    { id: 'Asia - Tomsk', text: 'Asia - Tomsk' },
    { id: 'Asia - Ujung Pandang', text: 'Asia - Ujung Pandang' },
    { id: 'Asia - Ulaanbaatar', text: 'Asia - Ulaanbaatar' },
    { id: 'Asia - Ulan Bator', text: 'Asia - Ulan Bator' },
    { id: 'Asia - Urumqi', text: 'Asia - Urumqi' },
    { id: 'Asia - Ust-Nera', text: 'Asia - Ust-Nera' },
    { id: 'Asia - Vientiane', text: 'Asia - Vientiane' },
    { id: 'Asia - Vladivostok', text: 'Asia - Vladivostok' },
    { id: 'Asia - Yakutsk', text: 'Asia - Yakutsk' },
    { id: 'Asia - Yangon', text: 'Asia - Yangon' },
    { id: 'Asia - Yekaterinburg', text: 'Asia - Yekaterinburg' },
    { id: 'Asia - Yerevan', text: 'Asia - Yerevan' },
    { id: 'Atlantic - Azores', text: 'Atlantic - Azores' },
    { id: 'Atlantic - Bermuda', text: 'Atlantic - Bermuda' },
    { id: 'Atlantic - Canary', text: 'Atlantic - Canary' },
    { id: 'Atlantic - Cape Verde', text: 'Atlantic - Cape Verde' },
    { id: 'Atlantic - Faeroe', text: 'Atlantic - Faeroe' },
    { id: 'Atlantic - Faroe', text: 'Atlantic - Faroe' },
    { id: 'Atlantic - Jan Mayen', text: 'Atlantic - Jan Mayen' },
    { id: 'Atlantic - Madeira', text: 'Atlantic - Madeira' },
    { id: 'Atlantic - Reykjavik', text: 'Atlantic - Reykjavik' },
    { id: 'Atlantic - South Georgia', text: 'Atlantic - South Georgia' },
    { id: 'Atlantic - St Helena', text: 'Atlantic - St Helena' },
    { id: 'Atlantic - Stanley', text: 'Atlantic - Stanley' },
    { id: 'Australia - ACT', text: 'Australia - ACT' },
    { id: 'Australia - Adelaide', text: 'Australia - Adelaide' },
    { id: 'Australia - Brisbane', text: 'Australia - Brisbane' },
    { id: 'Australia - Broken Hill', text: 'Australia - Broken Hill' },
    { id: 'Australia - Canberra', text: 'Australia - Canberra' },
    { id: 'Australia - Currie', text: 'Australia - Currie' },
    { id: 'Australia - Darwin', text: 'Australia - Darwin' },
    { id: 'Australia - Eucla', text: 'Australia - Eucla' },
    { id: 'Australia - Hobart', text: 'Australia - Hobart' },
    { id: 'Australia - LHI', text: 'Australia - LHI' },
    { id: 'Australia - Lindeman', text: 'Australia - Lindeman' },
    { id: 'Australia - Lord Howe', text: 'Australia - Lord Howe' },
    { id: 'Australia - Melbourne', text: 'Australia - Melbourne' },
    { id: 'Australia - NSW', text: 'Australia - NSW' },
    { id: 'Australia - North', text: 'Australia - North' },
    { id: 'Australia - Perth', text: 'Australia - Perth' },
    { id: 'Australia - Queensland', text: 'Australia - Queensland' },
    { id: 'Australia - South', text: 'Australia - South' },
    { id: 'Australia - Sydney', text: 'Australia - Sydney' },
    { id: 'Australia - Tasmania', text: 'Australia - Tasmania' },
    { id: 'Australia - Victoria', text: 'Australia - Victoria' },
    { id: 'Australia - West', text: 'Australia - West' },
    { id: 'Australia - Yancowinna', text: 'Australia - Yancowinna' },
    { id: 'Brazil - Acre', text: 'Brazil - Acre' },
    { id: 'Brazil - De Noronha', text: 'Brazil - De Noronha' },
    { id: 'Brazil - East', text: 'Brazil - East' },
    { id: 'Brazil - West', text: 'Brazil - West' },
    { id: 'CET', text: 'CET' },
    { id: 'CST6CDT', text: 'CST6CDT' },
    { id: 'Canada - Atlantic', text: 'Canada - Atlantic' },
    { id: 'Canada - Central', text: 'Canada - Central' },
    { id: 'Canada - Eastern', text: 'Canada - Eastern' },
    { id: 'Canada - Mountain', text: 'Canada - Mountain' },
    { id: 'Canada - Newfoundland', text: 'Canada - Newfoundland' },
    { id: 'Canada - Pacific', text: 'Canada - Pacific' },
    { id: 'Canada - Saskatchewan', text: 'Canada - Saskatchewan' },
    { id: 'Canada - Yukon', text: 'Canada - Yukon' },
    { id: 'Chile - Continental', text: 'Chile - Continental' },
    { id: 'Chile - Easter Island', text: 'Chile - Easter Island' },
    { id: 'Cuba', text: 'Cuba' },
    { id: 'EET', text: 'EET' },
    { id: 'EST', text: 'EST' },
    { id: 'EST5EDT', text: 'EST5EDT' },
    { id: 'Egypt', text: 'Egypt' },
    { id: 'Eire', text: 'Eire' },
    { id: 'Etc - GMT', text: 'Etc - GMT' },
    { id: 'Etc - GMT+0', text: 'Etc - GMT+0' },
    { id: 'Etc - GMT+1', text: 'Etc - GMT+1' },
    { id: 'Etc - GMT+10', text: 'Etc - GMT+10' },
    { id: 'Etc - GMT+11', text: 'Etc - GMT+11' },
    { id: 'Etc - GMT+12', text: 'Etc - GMT+12' },
    { id: 'Etc - GMT+2', text: 'Etc - GMT+2' },
    { id: 'Etc - GMT+3', text: 'Etc - GMT+3' },
    { id: 'Etc - GMT+4', text: 'Etc - GMT+4' },
    { id: 'Etc - GMT+5', text: 'Etc - GMT+5' },
    { id: 'Etc - GMT+6', text: 'Etc - GMT+6' },
    { id: 'Etc - GMT+7', text: 'Etc - GMT+7' },
    { id: 'Etc - GMT+8', text: 'Etc - GMT+8' },
    { id: 'Etc - GMT+9', text: 'Etc - GMT+9' },
    { id: 'Etc - GMT-0', text: 'Etc - GMT-0' },
    { id: 'Etc - GMT-1', text: 'Etc - GMT-1' },
    { id: 'Etc - GMT-10', text: 'Etc - GMT-10' },
    { id: 'Etc - GMT-11', text: 'Etc - GMT-11' },
    { id: 'Etc - GMT-12', text: 'Etc - GMT-12' },
    { id: 'Etc - GMT-13', text: 'Etc - GMT-13' },
    { id: 'Etc - GMT-14', text: 'Etc - GMT-14' },
    { id: 'Etc - GMT-2', text: 'Etc - GMT-2' },
    { id: 'Etc - GMT-3', text: 'Etc - GMT-3' },
    { id: 'Etc - GMT-4', text: 'Etc - GMT-4' },
    { id: 'Etc - GMT-5', text: 'Etc - GMT-5' },
    { id: 'Etc - GMT-6', text: 'Etc - GMT-6' },
    { id: 'Etc - GMT-7', text: 'Etc - GMT-7' },
    { id: 'Etc - GMT-8', text: 'Etc - GMT-8' },
    { id: 'Etc - GMT-9', text: 'Etc - GMT-9' },
    { id: 'Etc - GMT0', text: 'Etc - GMT0' },
    { id: 'Etc - Greenwich', text: 'Etc - Greenwich' },
    { id: 'Etc - UCT', text: 'Etc - UCT' },
    { id: 'Etc - UTC', text: 'Etc - UTC' },
    { id: 'Etc - Universal', text: 'Etc - Universal' },
    { id: 'Etc - Zulu', text: 'Etc - Zulu' },
    { id: 'Europe - Amsterdam', text: 'Europe - Amsterdam' },
    { id: 'Europe - Andorra', text: 'Europe - Andorra' },
    { id: 'Europe - Astrakhan', text: 'Europe - Astrakhan' },
    { id: 'Europe - Athens', text: 'Europe - Athens' },
    { id: 'Europe - Belfast', text: 'Europe - Belfast' },
    { id: 'Europe - Belgrade', text: 'Europe - Belgrade' },
    { id: 'Europe - Berlin', text: 'Europe - Berlin' },
    { id: 'Europe - Bratislava', text: 'Europe - Bratislava' },
    { id: 'Europe - Brussels', text: 'Europe - Brussels' },
    { id: 'Europe - Bucharest', text: 'Europe - Bucharest' },
    { id: 'Europe - Budapest', text: 'Europe - Budapest' },
    { id: 'Europe - Busingen', text: 'Europe - Busingen' },
    { id: 'Europe - Chisinau', text: 'Europe - Chisinau' },
    { id: 'Europe - Copenhagen', text: 'Europe - Copenhagen' },
    { id: 'Europe - Dublin', text: 'Europe - Dublin' },
    { id: 'Europe - Gibraltar', text: 'Europe - Gibraltar' },
    { id: 'Europe - Guernsey', text: 'Europe - Guernsey' },
    { id: 'Europe - Helsinki', text: 'Europe - Helsinki' },
    { id: 'Europe - Isle of Man', text: 'Europe - Isle of Man' },
    { id: 'Europe - Istanbul', text: 'Europe - Istanbul' },
    { id: 'Europe - Jersey', text: 'Europe - Jersey' },
    { id: 'Europe - Kaliningrad', text: 'Europe - Kaliningrad' },
    { id: 'Europe - Kiev', text: 'Europe - Kiev' },
    { id: 'Europe - Kirov', text: 'Europe - Kirov' },
    { id: 'Europe - Lisbon', text: 'Europe - Lisbon' },
    { id: 'Europe - Ljubljana', text: 'Europe - Ljubljana' },
    { id: 'Europe - London', text: 'Europe - London' },
    { id: 'Europe - Luxembourg', text: 'Europe - Luxembourg' },
    { id: 'Europe - Madrid', text: 'Europe - Madrid' },
    { id: 'Europe - Malta', text: 'Europe - Malta' },
    { id: 'Europe - Mariehamn', text: 'Europe - Mariehamn' },
    { id: 'Europe - Minsk', text: 'Europe - Minsk' },
    { id: 'Europe - Monaco', text: 'Europe - Monaco' },
    { id: 'Europe - Moscow', text: 'Europe - Moscow' },
    { id: 'Europe - Nicosia', text: 'Europe - Nicosia' },
    { id: 'Europe - Oslo', text: 'Europe - Oslo' },
    { id: 'Europe - Paris', text: 'Europe - Paris' },
    { id: 'Europe - Podgorica', text: 'Europe - Podgorica' },
    { id: 'Europe - Prague', text: 'Europe - Prague' },
    { id: 'Europe - Riga', text: 'Europe - Riga' },
    { id: 'Europe - Rome', text: 'Europe - Rome' },
    { id: 'Europe - Samara', text: 'Europe - Samara' },
    { id: 'Europe - San Marino', text: 'Europe - San Marino' },
    { id: 'Europe - Sarajevo', text: 'Europe - Sarajevo' },
    { id: 'Europe - Saratov', text: 'Europe - Saratov' },
    { id: 'Europe - Simferopol', text: 'Europe - Simferopol' },
    { id: 'Europe - Skopje', text: 'Europe - Skopje' },
    { id: 'Europe - Sofia', text: 'Europe - Sofia' },
    { id: 'Europe - Stockholm', text: 'Europe - Stockholm' },
    { id: 'Europe - Tallinn', text: 'Europe - Tallinn' },
    { id: 'Europe - Tirane', text: 'Europe - Tirane' },
    { id: 'Europe - Tiraspol', text: 'Europe - Tiraspol' },
    { id: 'Europe - Ulyanovsk', text: 'Europe - Ulyanovsk' },
    { id: 'Europe - Uzhgorod', text: 'Europe - Uzhgorod' },
    { id: 'Europe - Vaduz', text: 'Europe - Vaduz' },
    { id: 'Europe - Vatican', text: 'Europe - Vatican' },
    { id: 'Europe - Vienna', text: 'Europe - Vienna' },
    { id: 'Europe - Vilnius', text: 'Europe - Vilnius' },
    { id: 'Europe - Volgograd', text: 'Europe - Volgograd' },
    { id: 'Europe - Warsaw', text: 'Europe - Warsaw' },
    { id: 'Europe - Zagreb', text: 'Europe - Zagreb' },
    { id: 'Europe - Zaporozhye', text: 'Europe - Zaporozhye' },
    { id: 'Europe - Zurich', text: 'Europe - Zurich' },
    { id: 'Factory', text: 'Factory' },
    { id: 'GB', text: 'GB' },
    { id: 'GB-Eire', text: 'GB-Eire' },
    { id: 'GMT', text: 'GMT' },
    { id: 'GMT+0', text: 'GMT+0' },
    { id: 'GMT-0', text: 'GMT-0' },
    { id: 'GMT0', text: 'GMT0' },
    { id: 'Greenwich', text: 'Greenwich' },
    { id: 'HST', text: 'HST' },
    { id: 'Hongkong', text: 'Hongkong' },
    { id: 'Iceland', text: 'Iceland' },
    { id: 'Indian - Antananarivo', text: 'Indian - Antananarivo' },
    { id: 'Indian - Chagos', text: 'Indian - Chagos' },
    { id: 'Indian - Christmas', text: 'Indian - Christmas' },
    { id: 'Indian - Cocos', text: 'Indian - Cocos' },
    { id: 'Indian - Comoro', text: 'Indian - Comoro' },
    { id: 'Indian - Kerguelen', text: 'Indian - Kerguelen' },
    { id: 'Indian - Mahe', text: 'Indian - Mahe' },
    { id: 'Indian - Maldives', text: 'Indian - Maldives' },
    { id: 'Indian - Mauritius', text: 'Indian - Mauritius' },
    { id: 'Indian - Mayotte', text: 'Indian - Mayotte' },
    { id: 'Indian - Reunion', text: 'Indian - Reunion' },
    { id: 'Iran', text: 'Iran' },
    { id: 'Israel', text: 'Israel' },
    { id: 'Jamaica', text: 'Jamaica' },
    { id: 'Japan', text: 'Japan' },
    { id: 'Kwajalein', text: 'Kwajalein' },
    { id: 'Libya', text: 'Libya' },
    { id: 'MET', text: 'MET' },
    { id: 'MST', text: 'MST' },
    { id: 'MST7MDT', text: 'MST7MDT' },
    { id: 'Mexico - Baja Norte', text: 'Mexico - Baja Norte' },
    { id: 'Mexico - Baja Sur', text: 'Mexico - Baja Sur' },
    { id: 'Mexico - General', text: 'Mexico - General' },
    { id: 'NZ', text: 'NZ' },
    { id: 'NZ-CHAT', text: 'NZ-CHAT' },
    { id: 'Navajo', text: 'Navajo' },
    { id: 'PRC', text: 'PRC' },
    { id: 'PST8PDT', text: 'PST8PDT' },
    { id: 'Pacific - Apia', text: 'Pacific - Apia' },
    { id: 'Pacific - Auckland', text: 'Pacific - Auckland' },
    { id: 'Pacific - Bougainville', text: 'Pacific - Bougainville' },
    { id: 'Pacific - Chatham', text: 'Pacific - Chatham' },
    { id: 'Pacific - Chuuk', text: 'Pacific - Chuuk' },
    { id: 'Pacific - Easter', text: 'Pacific - Easter' },
    { id: 'Pacific - Efate', text: 'Pacific - Efate' },
    { id: 'Pacific - Enderbury', text: 'Pacific - Enderbury' },
    { id: 'Pacific - Fakaofo', text: 'Pacific - Fakaofo' },
    { id: 'Pacific - Fiji', text: 'Pacific - Fiji' },
    { id: 'Pacific - Funafuti', text: 'Pacific - Funafuti' },
    { id: 'Pacific - Galapagos', text: 'Pacific - Galapagos' },
    { id: 'Pacific - Gambier', text: 'Pacific - Gambier' },
    { id: 'Pacific - Guadalcanal', text: 'Pacific - Guadalcanal' },
    { id: 'Pacific - Guam', text: 'Pacific - Guam' },
    { id: 'Pacific - Honolulu', text: 'Pacific - Honolulu' },
    { id: 'Pacific - Johnston', text: 'Pacific - Johnston' },
    { id: 'Pacific - Kiritimati', text: 'Pacific - Kiritimati' },
    { id: 'Pacific - Kosrae', text: 'Pacific - Kosrae' },
    { id: 'Pacific - Kwajalein', text: 'Pacific - Kwajalein' },
    { id: 'Pacific - Majuro', text: 'Pacific - Majuro' },
    { id: 'Pacific - Marquesas', text: 'Pacific - Marquesas' },
    { id: 'Pacific - Midway', text: 'Pacific - Midway' },
    { id: 'Pacific - Nauru', text: 'Pacific - Nauru' },
    { id: 'Pacific - Niue', text: 'Pacific - Niue' },
    { id: 'Pacific - Norfolk', text: 'Pacific - Norfolk' },
    { id: 'Pacific - Noumea', text: 'Pacific - Noumea' },
    { id: 'Pacific - Pago Pago', text: 'Pacific - Pago Pago' },
    { id: 'Pacific - Palau', text: 'Pacific - Palau' },
    { id: 'Pacific - Pitcairn', text: 'Pacific - Pitcairn' },
    { id: 'Pacific - Pohnpei', text: 'Pacific - Pohnpei' },
    { id: 'Pacific - Ponape', text: 'Pacific - Ponape' },
    { id: 'Pacific - Port Moresby', text: 'Pacific - Port Moresby' },
    { id: 'Pacific - Rarotonga', text: 'Pacific - Rarotonga' },
    { id: 'Pacific - Saipan', text: 'Pacific - Saipan' },
    { id: 'Pacific - Samoa', text: 'Pacific - Samoa' },
    { id: 'Pacific - Tahiti', text: 'Pacific - Tahiti' },
    { id: 'Pacific - Tarawa', text: 'Pacific - Tarawa' },
    { id: 'Pacific - Tongatapu', text: 'Pacific - Tongatapu' },
    { id: 'Pacific - Truk', text: 'Pacific - Truk' },
    { id: 'Pacific - Wake', text: 'Pacific - Wake' },
    { id: 'Pacific - Wallis', text: 'Pacific - Wallis' },
    { id: 'Pacific - Yap', text: 'Pacific - Yap' },
    { id: 'Poland', text: 'Poland' },
    { id: 'Portugal', text: 'Portugal' },
    { id: 'ROC', text: 'ROC' },
    { id: 'ROK', text: 'ROK' },
    { id: 'Singapore', text: 'Singapore' },
    { id: 'Turkey', text: 'Turkey' },
    { id: 'UCT', text: 'UCT' },
    { id: 'US - Alaska', text: 'US - Alaska' },
    { id: 'US - Aleutian', text: 'US - Aleutian' },
    { id: 'US - Arizona', text: 'US - Arizona' },
    { id: 'US - Central', text: 'US - Central' },
    { id: 'US - East-Indiana', text: 'US - East-Indiana' },
    { id: 'US - Eastern', text: 'US - Eastern' },
    { id: 'US - Hawaii', text: 'US - Hawaii' },
    { id: 'US - Indiana-Starke', text: 'US - Indiana-Starke' },
    { id: 'US - Michigan', text: 'US - Michigan' },
    { id: 'US - Mountain', text: 'US - Mountain' },
    { id: 'US - Pacific', text: 'US - Pacific' },
    { id: 'US - Pacific-New', text: 'US - Pacific-New' },
    { id: 'US - Samoa', text: 'US - Samoa' },
    { id: 'UTC', text: 'UTC' },
    { id: 'Universal', text: 'Universal' },
    { id: 'W-SU', text: 'W-SU' },
    { id: 'WET', text: 'WET' },
    { id: 'Zulu', text: 'Zulu' },
  ];

  var languages = [
    { id: 'none', text: 'Choose a language...' },
    { id: 'Arabic', text: 'Arabic' },
    { id: 'Brazilian Portuguese', text: 'Brazilian Portuguese' },
    { id: 'Danish', text: 'Danish' },
    { id: 'Dutch', text: 'Dutch' },
    { id: 'English', text: 'English' },
    { id: 'Finnish', text: 'Finnish' },
    { id: 'French', text: 'French' },
    { id: 'German', text: 'German' },
    { id: 'Hebrew', text: 'Hebrew' },
    { id: 'Italian', text: 'Italian' },
    { id: 'Japanese', text: 'Japanese' },
    { id: 'Latin American Spanish', text: 'Latin American Spanish' },
    { id: 'Norwegian', text: 'Norwegian' },
    { id: 'Spanish', text: 'Spanish' },
    { id: 'Swedish', text: 'Swedish' },
  ]

  var currencies = [
    { id: 'none', text: 'Choose a currency...' },
    { id: 'USD - US Dollar', text: 'USD - US Dollar' },
    { id: 'AED - United Arab Emirates Dirham', text: 'AED - United Arab Emirates Dirham' },
    { id: 'AFN - Afghan Afghani', text: 'AFN - Afghan Afghani' },
    { id: 'ALL - Albanian Lek', text: 'ALL - Albanian Lek' },
    { id: 'AMD - Armenian Dram', text: 'AMD - Armenian Dram' },
    { id: 'ANG - Netherlands Antillean Guilder', text: 'ANG - Netherlands Antillean Guilder' },
    { id: 'AOA - Angolan Kwanza', text: 'AOA - Angolan Kwanza' },
    { id: 'ARS - Argentine Peso', text: 'ARS - Argentine Peso' },
    { id: 'AUD - Australian Dollar', text: 'AUD - Australian Dollar' },
    { id: 'AWG - Aruban Florin', text: 'AWG - Aruban Florin' },
    { id: 'AZN - Azerbaijani Manat', text: 'AZN - Azerbaijani Manat' },
    { id: 'BAM - Bosnia-Herzegovina Convertible Mark', text: 'BAM - Bosnia-Herzegovina Convertible Mark' },
    { id: 'BBD - Barbadian Dollar', text: 'BBD - Barbadian Dollar' },
    { id: 'BDT - Bangladeshi Taka', text: 'BDT - Bangladeshi Taka' },
    { id: 'BGN - Bulgarian Lev', text: 'BGN - Bulgarian Lev' },
    { id: 'BIF - Burundian Franc', text: 'BIF - Burundian Franc' },
    { id: 'BMD - Bermudan Dollar', text: 'BMD - Bermudan Dollar' },
    { id: 'BND - Brunei Dollar', text: 'BND - Brunei Dollar' },
    { id: 'BOB - Bolivian Boliviano', text: 'BOB - Bolivian Boliviano' },
    { id: 'BRL - Brazilian Real', text: 'BRL - Brazilian Real' },
    { id: 'BSD - Bahamian Dollar', text: 'BSD - Bahamian Dollar' },
    { id: 'BWP - Botswanan Pula', text: 'BWP - Botswanan Pula' },
    { id: 'BZD - Belize Dollar', text: 'BZD - Belize Dollar' },
    { id: 'CAD - Canadian Dollar', text: 'CAD - Canadian Dollar' },
    { id: 'CDF - Congolese Franc', text: 'CDF - Congolese Franc' },
    { id: 'CHF - Swiss Franc', text: 'CHF - Swiss Franc' },
    { id: 'CLP - Chilean Peso', text: 'CLP - Chilean Peso' },
    { id: 'CNY - Chinese Yuan', text: 'CNY - Chinese Yuan' },
    { id: 'COP - Colombian Peso', text: 'COP - Colombian Peso' },
    { id: 'CRC - Costa Rican Colón', text: 'CRC - Costa Rican Colón' },
    { id: 'CVE - Cape Verdean Escudo', text: 'CVE - Cape Verdean Escudo' },
    { id: 'CZK - Czech Koruna', text: 'CZK - Czech Koruna' },
    { id: 'DJF - Djiboutian Franc', text: 'DJF - Djiboutian Franc' },
    { id: 'DKK - Danish Krone', text: 'DKK - Danish Krone' },
    { id: 'DOP - Dominican Peso', text: 'DOP - Dominican Peso' },
    { id: 'DZD - Algerian Dinar', text: 'DZD - Algerian Dinar' },
    { id: 'EGP - Egyptian Pound', text: 'EGP - Egyptian Pound' },
    { id: 'ETB - Ethiopian Birr', text: 'ETB - Ethiopian Birr' },
    { id: 'EUR - Euro', text: 'EUR - Euro' },
    { id: 'FJD - Fijian Dollar', text: 'FJD - Fijian Dollar' },
    { id: 'FKP - Falkland Islands Pound', text: 'FKP - Falkland Islands Pound' },
    { id: 'GBP - British Pound', text: 'GBP - British Pound' },
    { id: 'GEL - Georgian Lari', text: 'GEL - Georgian Lari' },
    { id: 'GIP - Gibraltar Pound', text: 'GIP - Gibraltar Pound' },
    { id: 'GMD - Gambian Dalasi', text: 'GMD - Gambian Dalasi' },
    { id: 'GNF - Guinean Franc', text: 'GNF - Guinean Franc' },
    { id: 'GTQ - Guatemalan Quetzal', text: 'GTQ - Guatemalan Quetzal' },
    { id: 'GYD - Guyanaese Dollar', text: 'GYD - Guyanaese Dollar' },
    { id: 'HKD - Hong Kong Dollar', text: 'HKD - Hong Kong Dollar' },
    { id: 'HNL - Honduran Lempira', text: 'HNL - Honduran Lempira' },
    { id: 'HRK - Croatian Kuna', text: 'HRK - Croatian Kuna' },
    { id: 'HTG - Haitian Gourde', text: 'HTG - Haitian Gourde' },
    { id: 'HUF - Hungarian Forint', text: 'HUF - Hungarian Forint' },
    { id: 'IDR - Indonesian Rupiah', text: 'IDR - Indonesian Rupiah' },
    { id: 'ILS - Israeli New Shekel', text: 'ILS - Israeli New Shekel' },
    { id: 'INR - Indian Rupee', text: 'INR - Indian Rupee' },
    { id: 'ISK - Icelandic Króna', text: 'ISK - Icelandic Króna' },
    { id: 'JMD - Jamaican Dollar', text: 'JMD - Jamaican Dollar' },
    { id: 'JPY - Japanese Yen', text: 'JPY - Japanese Yen' },
    { id: 'KES - Kenyan Shilling', text: 'KES - Kenyan Shilling' },
    { id: 'KGS - Kyrgystani Som', text: 'KGS - Kyrgystani Som' },
    { id: 'KHR - Cambodian Riel', text: 'KHR - Cambodian Riel' },
    { id: 'KMF - Comorian Franc', text: 'KMF - Comorian Franc' },
    { id: 'KRW - South Korean Won', text: 'KRW - South Korean Won' },
    { id: 'KYD - Cayman Islands Dollar', text: 'KYD - Cayman Islands Dollar' },
    { id: 'KZT - Kazakhstani Tenge', text: 'KZT - Kazakhstani Tenge' },
    { id: 'LAK - Laotian Kip', text: 'LAK - Laotian Kip' },
    { id: 'LBP - Lebanese Pound', text: 'LBP - Lebanese Pound' },
    { id: 'LKR - Sri Lankan Rupee', text: 'LKR - Sri Lankan Rupee' },
    { id: 'LRD - Liberian Dollar', text: 'LRD - Liberian Dollar' },
    { id: 'LSL - Lesotho Loti', text: 'LSL - Lesotho Loti' },
    { id: 'MAD - Moroccan Dirham', text: 'MAD - Moroccan Dirham' },
    { id: 'MDL - Moldovan Leu', text: 'MDL - Moldovan Leu' },
    { id: 'MGA - Malagasy Ariary', text: 'MGA - Malagasy Ariary' },
    { id: 'MKD - Macedonian Denar', text: 'MKD - Macedonian Denar' },
    { id: 'MMK - Myanmar Kyat', text: 'MMK - Myanmar Kyat' },
    { id: 'MNT - Mongolian Tugrik', text: 'MNT - Mongolian Tugrik' },
    { id: 'MOP - Macanese Pataca', text: 'MOP - Macanese Pataca' },
    { id: 'MRO - Mauritanian Ouguiya (1973–2017', text: 'MRO - Mauritanian Ouguiya (1973–2017' },
    { id: 'MUR - Mauritian Rupee', text: 'MUR - Mauritian Rupee' },
    { id: 'MVR - Maldivian Rufiyaa', text: 'MVR - Maldivian Rufiyaa' },
    { id: 'MWK - Malawian Kwacha', text: 'MWK - Malawian Kwacha' },
    { id: 'MXN - Mexican Peso', text: 'MXN - Mexican Peso' },
    { id: 'MYR - Malaysian Ringgit', text: 'MYR - Malaysian Ringgit' },
    { id: 'MZN - Mozambican Metical', text: 'MZN - Mozambican Metical' },
    { id: 'NAD - Namibian Dollar', text: 'NAD - Namibian Dollar' },
    { id: 'NGN - Nigerian Naira', text: 'NGN - Nigerian Naira' },
    { id: 'NIO - Nicaraguan Córdoba', text: 'NIO - Nicaraguan Córdoba' },
    { id: 'NOK - Norwegian Krone', text: 'NOK - Norwegian Krone' },
    { id: 'NPR - Nepalese Rupee', text: 'NPR - Nepalese Rupee' },
    { id: 'NZD - New Zealand Dollar', text: 'NZD - New Zealand Dollar' },
    { id: 'PAB - Panamanian Balboa', text: 'PAB - Panamanian Balboa' },
    { id: 'PEN - Peruvian Sol', text: 'PEN - Peruvian Sol' },
    { id: 'PGK - Papua New Guinean Kina', text: 'PGK - Papua New Guinean Kina' },
    { id: 'PHP - Philippine Piso', text: 'PHP - Philippine Piso' },
    { id: 'PKR - Pakistani Rupee', text: 'PKR - Pakistani Rupee' },
    { id: 'PLN - Polish Zloty', text: 'PLN - Polish Zloty' },
    { id: 'PYG - Paraguayan Guarani', text: 'PYG - Paraguayan Guarani' },
    { id: 'QAR - Qatari Rial', text: 'QAR - Qatari Rial' },
    { id: 'RON - Romanian Leu', text: 'RON - Romanian Leu' },
    { id: 'RSD - Serbian Dinar', text: 'RSD - Serbian Dinar' },
    { id: 'RUB - Russian Ruble', text: 'RUB - Russian Ruble' },
    { id: 'RWF - Rwandan Franc', text: 'RWF - Rwandan Franc' },
    { id: 'SAR - Saudi Riyal', text: 'SAR - Saudi Riyal' },
    { id: 'SBD - Solomon Islands Dollar', text: 'SBD - Solomon Islands Dollar' },
    { id: 'SCR - Seychellois Rupee', text: 'SCR - Seychellois Rupee' },
    { id: 'SEK - Swedish Krona', text: 'SEK - Swedish Krona' },
    { id: 'SGD - Singapore Dollar', text: 'SGD - Singapore Dollar' },
    { id: 'SHP - St. Helena Pound', text: 'SHP - St. Helena Pound' },
    { id: 'SLL - Sierra Leonean Leone', text: 'SLL - Sierra Leonean Leone' },
    { id: 'SOS - Somali Shilling', text: 'SOS - Somali Shilling' },
    { id: 'SRD - Surinamese Dollar', text: 'SRD - Surinamese Dollar' },
    { id: 'STD - São Tomé &amp; Príncipe Dobra (1977–2017', text: 'STD - São Tomé &amp; Príncipe Dobra (1977–2017' },
    { id: 'SZL - Swazi Lilangeni', text: 'SZL - Swazi Lilangeni' },
    { id: 'THB - Thai Baht', text: 'THB - Thai Baht' },
    { id: 'TJS - Tajikistani Somoni', text: 'TJS - Tajikistani Somoni' },
    { id: 'TOP - Tongan Paʻanga', text: 'TOP - Tongan Paʻanga' },
    { id: 'TRY - Turkish Lira', text: 'TRY - Turkish Lira' },
    { id: 'TTD - Trinidad &amp; Tobago Dollar', text: 'TTD - Trinidad &amp; Tobago Dollar' },
    { id: 'TWD - New Taiwan Dollar', text: 'TWD - New Taiwan Dollar' },
    { id: 'TZS - Tanzanian Shilling', text: 'TZS - Tanzanian Shilling' },
    { id: 'UAH - Ukrainian Hryvnia', text: 'UAH - Ukrainian Hryvnia' },
    { id: 'UGX - Ugandan Shilling', text: 'UGX - Ugandan Shilling' },
    { id: 'UYU - Uruguayan Peso', text: 'UYU - Uruguayan Peso' },
    { id: 'UZS - Uzbekistani Som', text: 'UZS - Uzbekistani Som' },
    { id: 'VND - Vietnamese Dong', text: 'VND - Vietnamese Dong' },
    { id: 'VUV - Vanuatu Vatu', text: 'VUV - Vanuatu Vatu' },
    { id: 'WST - Samoan Tala', text: 'WST - Samoan Tala' },
    { id: 'XAF - Central African CFA Franc', text: 'XAF - Central African CFA Franc' },
    { id: 'XCD - East Caribbean Dollar', text: 'XCD - East Caribbean Dollar' },
    { id: 'XOF - West African CFA Franc', text: 'XOF - West African CFA Franc' },
    { id: 'XPF - CFP Franc', text: 'XPF - CFP Franc' },
    { id: 'YER - Yemeni Rial', text: 'YER - Yemeni Rial' },
    { id: 'ZAR - South African Rand', text: 'ZAR - South African Rand' },
    { id: 'ZMW - Zambian Kwacha', text: 'ZMW - Zambian Kwacha' },
  ]

  var taxes = [
    { id: 'exempt', text: 'Exempt' },
    { id: 'reverse', text: 'Reverse charge' },
    { id: 'none', text: 'Taxable' },
  ]

  var tax_ids = [
    { id: 'none', text: 'Select ID type...' },
    { id: 'AE TRN', text: 'AE TRN' },
    { id: 'United Arab Emirates', text: 'United Arab Emirates' },
    { id: 'AT VAT', text: 'AT VAT' },
    { id: 'AU ABN', text: 'AU ABN' },
    { id: 'BE VAT', text: 'BE VAT' },
    { id: 'BG VAT', text: 'BG VAT' },
    { id: 'BR CNPJ', text: 'BR CNPJ' },
    { id: 'BR CPF', text: 'BR CPF' },
    { id: 'CA BN', text: 'CA BN' },
    { id: 'CA QST', text: 'CA QST' },
    { id: 'CH VAT', text: 'CH VAT' },
    { id: 'CL TIN', text: 'CL TIN' },
    { id: 'CY VAT', text: 'CY VAT' },
    { id: 'CZ VAT', text: 'CZ VAT' },
    { id: 'Czech Republic', text: 'Czech Republic' },
    { id: 'DE VAT', text: 'DE VAT' },
    { id: 'DK VAT', text: 'DK VAT' },
    { id: 'EE VAT', text: 'EE VAT' },
    { id: 'ES CIF', text: 'ES CIF' },
    { id: 'ES VAT', text: 'ES VAT' },
    { id: 'FI VAT', text: 'FI VAT' },
    { id: 'FR VAT', text: 'FR VAT' },
    { id: 'GB VAT', text: 'GB VAT' },
    { id: 'United Kingdom', text: 'United Kingdom' },
    { id: 'GR VAT', text: 'GR VAT' },
    { id: 'HK BR', text: 'HK BR' },
    { id: 'Hong Kong SAR China', text: 'Hong Kong SAR China' },
    { id: 'HR VAT', text: 'HR VAT' },
    { id: 'HU VAT', text: 'HU VAT' },
    { id: 'ID NPWP', text: 'ID NPWP' },
    { id: 'IE VAT', text: 'IE VAT' },
    { id: 'IN GST', text: 'IN GST' },
    { id: 'IT VAT', text: 'IT VAT' },
    { id: 'JP CN', text: 'JP CN' },
    { id: 'JP RN', text: 'JP RN' },
    { id: 'KR BRN', text: 'KR BRN' },
    { id: 'South Korea', text: 'South Korea' },
    { id: 'LI UID', text: 'LI UID' },
    { id: 'LT VAT', text: 'LT VAT' },
    { id: 'LU VAT', text: 'LU VAT' },
    { id: 'LV VAT', text: 'LV VAT' },
    { id: 'MT VAT', text: 'MT VAT' },
    { id: 'MX RFC', text: 'MX RFC' },
    { id: 'MY FRP', text: 'MY FRP' },
    { id: 'MY ITN', text: 'MY ITN' },
    { id: 'MY SST', text: 'MY SST' },
    { id: 'NL VAT', text: 'NL VAT' },
    { id: 'NO VAT', text: 'NO VAT' },
    { id: 'NZ GST', text: 'NZ GST' },
    { id: 'New Zealand', text: 'New Zealand' },
    { id: 'PL VAT', text: 'PL VAT' },
    { id: 'PT VAT', text: 'PT VAT' },
    { id: 'RO VAT', text: 'RO VAT' },
    { id: 'RU INN', text: 'RU INN' },
    { id: 'RU KPP', text: 'RU KPP' },
    { id: 'SA VAT', text: 'SA VAT' },
    { id: 'Saudi Arabia', text: 'Saudi Arabia' },
    { id: 'SE VAT', text: 'SE VAT' },
    { id: 'SG GST', text: 'SG GST' },
    { id: 'SG UEN', text: 'SG UEN' },
    { id: 'SI VAT', text: 'SI VAT' },
    { id: 'SK VAT', text: 'SK VAT' },
    { id: 'TH VAT', text: 'TH VAT' },
    { id: 'TW VAT', text: 'TW VAT' },
    { id: 'US EIN', text: 'US EIN' },
    { id: 'United States', text: 'United States' },
    { id: 'ZA VAT', text: 'ZA VAT' },
    { id: 'South Africa', text: 'South Africa' },
  ]

  var x = 1;
  var taxnum = 1;
  var max_fields = 10;
  var option;
  var rules = {
    tax_account_number1: {
      required: true,
      minlength: 10,
      maxlength: 10,
      number: true,
    },
  };
  var msgs = {
    tax_account_number1: {
      required: "taxnum is required",
      minlength: "This tax ID is invalid.",
      maxlength: "This tax ID is invalid."
    }
  };

  $("#country_array").select2({
    dropdownAutoWidth: true,
    width: '100%',
    data: countries
  });

  $("#country_array2").select2({
    dropdownAutoWidth: true,
    width: '100%',
    data: countries
  });

  $("#country_array").change(function () {
    console.log('country', $(this).val())
    option = $(this).val()
    // countries[0] = { id: `${option}`, text: `${option}` }
    if (option == 'none') {
      $(".billing-details-hidden").hide()
    } else {
      $(".billing-details-hidden").show()
      // $("#country_array2").select2({
      //   dropdownAutoWidth: true,
      //   width: '100%',
      //   data: countries
      // });
      // $(".select2-selection__arrow").remove();
      // $(".select2-selection--single").append(`<div aria-hidden="true" style="position: absolute;top: 33%;right: 8px;z-index: 2;margin-top: -6px;transition: color .24s;pointer-events: none;" class=" SVGInline SVGInline--cleaned SVG Icon Icon--arrowUpDown SearchableSelect - arrows Icon - color Icon - color--gray600 Box - root Flex - flex"><svg aria-hidden="true" class="SVGInline - svg SVGInline--cleaned - svg SVG - svg Icon - svg Icon--arrowUpDown - svg SearchableSelect - arrows - svg Icon - color - svg Icon - color--gray600 - svg" height="12" width="12" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><path d="M11.891 9.992a1 1 0 1 1 1.416 1.415l-4.3 4.3a1 1 0 0 1-1.414 0l-4.3-4.3A1 1 0 0 1 4.71 9.992l3.59 3.591 3.591-3.591zm0-3.984L8.3 2.417 4.709 6.008a1 1 0 0 1-1.416-1.415l4.3-4.3a1 1 0 0 1 1.414 0l4.3 4.3a1 1 0 1 1-1.416 1.415z"></path></svg></div>`)
    }
  })

  $("#timezone_array").select2({
    dropdownAutoWidth: true,
    width: '100%',
    data: timezones
  });

  $("#language_array").select2({
    dropdownAutoWidth: true,
    width: '100%',
    data: languages
  });

  $("#currency_array").select2({
    dropdownAutoWidth: true,
    width: '100%',
    data: currencies
  });

  $("#tax_array").select2({
    dropdownAutoWidth: true,
    width: '100%',
    data: taxes
  });

  $("#tax_id_array").select2({
    dropdownAutoWidth: true,
    width: '100%',
    data: tax_ids
  });

  $(".add-taxtid").click(function (e) {
    e.preventDefault();
    if (x < max_fields) {
      x++;
      $(".parent-tax-info").first().append(`
      <div class="tax-id-info" id="tax-id-info_tax_account_number${x}">
        <div style="width: 40%;">
          <select name="tax_id${x}" class="form-control-sm form-control tax_account_number" id="tax_id_array${x}"></select>
        </div>
        <div style="width: 53%; position: relative;top: 2px;">
          <input name="tax_account_number${x}" onblur="start_validate('tax_account_number${x}')" onkeyup="validate('tax_account_number${x}')" type="text" id="tax_account_number${x}" class="form-control form-control-sm tax_account_number">
        </div>
        <div style="cursor: pointer; margin-left: 3px" class="remove_field">
          <svg margin="[object Object]" aria-hidden="true" class="SVGInline-svg SVGInline--cleaned-svg SVG-svg Icon-svg Icon--cancel-svg Icon-color-svg Icon-color--blue-svg" height="12" width="12" viewBox="0 0 16 16" xmlns="http://www.w3.org/2000/svg">
            <path d="M8 6.585l4.593-4.592a1 1 0 0 1 1.415 1.416L9.417 8l4.591 4.591a1 1 0 0 1-1.415 1.416L8 9.415l-4.592 4.592a1 1 0 0 1-1.416-1.416L6.584 8l-4.59-4.591a1 1 0 1 1 1.415-1.416z" fill-rule="evenodd"></path>
          </svg>
        </div>
      </div>`
      );
      $("#tax_id_array" + x).select2({
        dropdownAutoWidth: true,
        width: '100%',
        data: tax_ids
      });
      $(".select2-selection__arrow").remove();
      $(".select2-selection--single").append(`<div aria-hidden="true" style="position: absolute;top: 33%;right: 8px;z-index: 2;margin-top: -6px;transition: color .24s;pointer-events: none;" class=" SVGInline SVGInline--cleaned SVG Icon Icon--arrowUpDown SearchableSelect - arrows Icon - color Icon - color--gray600 Box - root Flex - flex"><svg aria-hidden="true" class="SVGInline - svg SVGInline--cleaned - svg SVG - svg Icon - svg Icon--arrowUpDown - svg SearchableSelect - arrows - svg Icon - color - svg Icon - color--gray600 - svg" height="12" width="12" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><path d="M11.891 9.992a1 1 0 1 1 1.416 1.415l-4.3 4.3a1 1 0 0 1-1.414 0l-4.3-4.3A1 1 0 0 1 4.71 9.992l3.59 3.591 3.591-3.591zm0-3.984L8.3 2.417 4.709 6.008a1 1 0 0 1-1.416-1.415l4.3-4.3a1 1 0 0 1 1.414 0l4.3 4.3a1 1 0 1 1-1.416 1.415z"></path></svg></div>`)
    }
  });

  $(".parent-tax-info").on("click", ".remove_field", function (e) {
    e.preventDefault(); $(this).parent('div').remove(); x--;
  })

  var input = document.querySelector("#phone");
  console.log('input', input)
  if (input != undefined) {
    window.intlTelInput(input, {
      separateDialCode: true,
      customPlaceholder: function (
        selectedCountryPlaceholder,
        selectedCountryData
      ) {
        return "e.g. " + selectedCountryPlaceholder;
      },
    });
  }

  $("#toggle-billing-info").click(function () {
    $("#billing-info").toggle()
    $("#toggle-billing-info svg").toggleClass('rotate-180')
  })

  $("#same_as_email").click(function () {
    $("#same_email").toggle()
  })

  $("#same_as_billing").click(function () {
    $("#same_billing").toggle()
  })

  $("#add_recipient").click(function () {
    $("#show_more").toggle()
    $("#add_recipient").toggle()
  })

  $(".showless").click(function () {
    $("#show-info").toggle()
    $(this).find("a").toggle()
  })



  $("#customer-add-form").submit(function () {
    event.preventDefault()
    console.log('customer-add-form', $(this).serialize())

    $.post('/customers', $(this).serialize(), function (res) {
      // console.log('res', res)
      if (res == "success") {
        // $('#customer-add-modal').modal('hide');
        location.reload();
      }
    })
  })

  $("#cancel").click(function () {
    $('#customer-add-modal').modal('hide');
  })

  $("#checkAll").click(function () {
    $("input[type=checkbox]").prop("checked", $(this).prop("checked"));
  })

  $(".select2-selection__arrow").remove();
  $(".select2-selection--single").append(`<div aria-hidden="true" style="position: absolute;top: 33%;right: 8px;z-index: 2;margin-top: -6px;transition: color .24s;pointer-events: none;" class=" SVGInline SVGInline--cleaned SVG Icon Icon--arrowUpDown SearchableSelect - arrows Icon - color Icon - color--gray600 Box - root Flex - flex"><svg aria-hidden="true" class="SVGInline - svg SVGInline--cleaned - svg SVG - svg Icon - svg Icon--arrowUpDown - svg SearchableSelect - arrows - svg Icon - color - svg Icon - color--gray600 - svg" height="12" width="12" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><path d="M11.891 9.992a1 1 0 1 1 1.416 1.415l-4.3 4.3a1 1 0 0 1-1.414 0l-4.3-4.3A1 1 0 0 1 4.71 9.992l3.59 3.591 3.591-3.591zm0-3.984L8.3 2.417 4.709 6.008a1 1 0 0 1-1.416-1.415l4.3-4.3a1 1 0 0 1 1.414 0l4.3 4.3a1 1 0 1 1-1.416 1.415z"></path></svg></div>`)

  //show page
  $("#toggle-details-info").click(function () {
    $("#details-info-a").toggle()
    $("#details-info").toggle()
    $("#toggle-details-info svg").toggleClass('rotate-90')
  })

  $("#toggle-metadata-info").click(function () {
    $("#metadata-info-a").toggle()
    $("#metadata-info").toggle()
    $("#toggle-metadata-info svg").toggleClass('rotate-90')
  })
})
